
apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-backend-service
  labels:
    app: python-backend-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: python-backend-service
  template:
    metadata:
      labels:
        app: python-backend-service
    spec:
      containers:
      - name: python-backend-service
        image: azizul2go/three-tier-backend:latest
        imagePullPolicy: Always
